version: '3.8'

services:
  # Service Backend Laravel (Production)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cesizen-backend
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=cesizen
      - DB_USERNAME=cesizen_user
      - DB_PASSWORD=cesizen_password
      - SESSION_DRIVER=file
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
    volumes:
      # Volume pour les logs Laravel
      - laravel_logs:/var/www/html/storage/logs
      # Volume pour le cache
      - laravel_cache:/var/www/html/storage/framework/cache
      # Volume pour les sessions
      - laravel_sessions:/var/www/html/storage/framework/sessions
    networks:
      - cesizen-network
    restart: unless-stopped
    depends_on:
      - mysql
    command: php artisan serve --host=0.0.0.0 --port=8000

  # Service Backend Laravel (Développement)
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cesizen-backend-dev
    ports:
      - "8001:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=cesizen
      - DB_USERNAME=cesizen_user
      - DB_PASSWORD=cesizen_password
      - SESSION_DRIVER=file
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
    volumes:
      # Volume pour le hot reload en développement
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
      # Volume pour les logs Laravel
      - laravel_logs:/var/www/html/storage/logs
      # Volume pour le cache
      - laravel_cache:/var/www/html/storage/framework/cache
      # Volume pour les sessions
      - laravel_sessions:/var/www/html/storage/framework/sessions
    networks:
      - cesizen-network
    restart: unless-stopped
    depends_on:
      - mysql
    profiles:
      - dev
    command: php artisan serve --host=0.0.0.0 --port=8000

  # Service MySQL
  mysql:
    image: mysql:8.0
    container_name: cesizen-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cesizen
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: cesizen_user
      MYSQL_PASSWORD: cesizen_password
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - cesizen-network
    command: --default-authentication-plugin=mysql_native_password

  # Service phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: cesizen-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password
      UPLOAD_LIMIT: 100M
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - cesizen-network

  # Service Redis (optionnel pour le cache et les queues)
  redis:
    image: redis:7-alpine
    container_name: cesizen-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cesizen-network
    profiles:
      - cache

  # Service Queue Worker (optionnel pour les tâches en arrière-plan)
  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cesizen-queue-worker
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=cesizen
      - DB_USERNAME=cesizen_user
      - DB_PASSWORD=cesizen_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - laravel_logs:/var/www/html/storage/logs
    networks:
      - cesizen-network
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    profiles:
      - cache
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600

volumes:
  mysql_data:
  laravel_logs:
  laravel_cache:
  laravel_sessions:
  redis_data:

networks:
  cesizen-network:
    driver: bridge
